ConvertFrom-StringData @'
    EvaluatingPermissionState = Evaluating cluster policy permission state for policy '{0}' in workspace '{1}'. (DCPP0001)
    PermissionNotFound = Cluster policy permissions for policy '{0}' not found in workspace. (DCPP0002)
    ErrorGettingPermission = Error getting cluster policy permissions for policy '{0}': {1}. (DCPP0003)
    UpdatingPermission = Updating cluster policy permissions for policy '{0}'. (DCPP0004)
    PermissionUpdated = Cluster policy permissions for policy '{0}' have been updated successfully. (DCPP0005)
    FailedToUpdatePermission = Failed to update cluster policy permissions for policy '{0}': {1}. (DCPP0006)
    CreatingPermission = Creating cluster policy permissions for policy '{0}'. (DCPP0007)
    PermissionCreated = Cluster policy permissions for policy '{0}' have been created successfully. (DCPP0008)
    FailedToCreatePermission = Failed to create cluster policy permissions for policy '{0}': {1}. (DCPP0009)
    InvalidWorkspaceUrl = The WorkspaceUrl '{0}' is not valid. It must start with 'https://'. (DCPP0010)
    RemovingPermission = Removing cluster policy permissions for policy '{0}'. (DCPP0011)
    PermissionRemoved = Cluster policy permissions for policy '{0}' have been removed successfully. (DCPP0012)
    FailedToRemovePermission = Failed to remove cluster policy permissions for policy '{0}': {1}. (DCPP0013)
    ClusterPolicyIdRequired = The ClusterPolicyId property is required and cannot be empty. (DCPP0014)
    InvalidUserName = The UserName '{0}' is not valid. UserName must contain an '@' character. (DCPP0015)
    InvalidServicePrincipalName = The ServicePrincipalName '{0}' is not valid. ServicePrincipalName must be a valid GUID. (DCPP0016)
    NoPrincipalSpecified = Each access control entry must specify exactly one principal (GroupName, UserName, or ServicePrincipalName). (DCPP0017)
    MultiplePrincipalsSpecified = Each access control entry must specify only one principal. Cannot specify multiple of GroupName, UserName, or ServicePrincipalName. (DCPP0018)
'@
