ConvertFrom-StringData @'
    EvaluatingWarehouseState = Evaluating SQL warehouse state for '{0}' in workspace '{1}'. (DSW0001)
    WarehouseNotFound = SQL warehouse '{0}' not found in workspace. (DSW0002)
    ErrorGettingWarehouse = Error getting SQL warehouse '{0}': {1}. (DSW0003)
    UpdatingWarehouse = Updating SQL warehouse '{0}'. (DSW0004)
    WarehouseUpdated = SQL warehouse '{0}' has been updated successfully. (DSW0005)
    FailedToUpdateWarehouse = Failed to update SQL warehouse '{0}': {1}. (DSW0006)
    CreatingWarehouse = Creating SQL warehouse '{0}'. (DSW0007)
    WarehouseCreated = SQL warehouse '{0}' has been created successfully. (DSW0008)
    FailedToCreateWarehouse = Failed to create SQL warehouse '{0}': {1}. (DSW0009)
    InvalidWorkspaceUrl = The WorkspaceUrl '{0}' is not valid. It must start with 'https://'. (DSW0010)
    RemovingWarehouse = Removing SQL warehouse '{0}'. (DSW0011)
    WarehouseRemoved = SQL warehouse '{0}' has been removed successfully. (DSW0012)
    FailedToRemoveWarehouse = Failed to remove SQL warehouse '{0}': {1}. (DSW0013)
    InvalidAutoStopMins = The AutoStopMins value '{0}' is not valid. It must be 0 (no autostop) or >= 10 minutes. (DSW0014)
    MaxClustersMustBeGreaterOrEqualToMin = MaxNumClusters ({0}) must be greater than or equal to MinNumClusters ({1}). (DSW0015)
    TooManyTags = Too many tags specified ({0}). Maximum allowed is 45. (DSW0016)
    ServerlessRequiresProWarehouseType = EnableServerlessCompute requires WarehouseType to be 'PRO'. (DSW0017)
    ExportingResources = Exporting {0} resources from Databricks workspace. (DSW0018)
    NoResourcesFound = No {0} resources found in Databricks workspace. (DSW0019)
    ExportFailed = Failed to export {0} resources: {1}. (DSW0020)
'@
