ConvertFrom-StringData @'
    EvaluatingPermissionState = Evaluating SQL warehouse permission state for warehouse '{0}' in workspace '{1}'. (DSWP0001)
    PermissionNotFound = SQL warehouse permissions for warehouse '{0}' not found in workspace. (DSWP0002)
    ErrorGettingPermission = Error getting SQL warehouse permissions for warehouse '{0}': {1}. (DSWP0003)
    UpdatingPermission = Updating SQL warehouse permissions for warehouse '{0}'. (DSWP0004)
    PermissionUpdated = SQL warehouse permissions for warehouse '{0}' have been updated successfully. (DSWP0005)
    FailedToUpdatePermission = Failed to update SQL warehouse permissions for warehouse '{0}': {1}. (DSWP0006)
    CreatingPermission = Creating SQL warehouse permissions for warehouse '{0}'. (DSWP0007)
    PermissionCreated = SQL warehouse permissions for warehouse '{0}' have been created successfully. (DSWP0008)
    FailedToCreatePermission = Failed to create SQL warehouse permissions for warehouse '{0}': {1}. (DSWP0009)
    InvalidWorkspaceUrl = The WorkspaceUrl '{0}' is not valid. It must start with 'https://'. (DSWP0010)
    RemovingPermission = Removing SQL warehouse permissions for warehouse '{0}'. (DSWP0011)
    PermissionRemoved = SQL warehouse permissions for warehouse '{0}' have been removed successfully. (DSWP0012)
    FailedToRemovePermission = Failed to remove SQL warehouse permissions for warehouse '{0}': {1}. (DSWP0013)
    WarehouseIdRequired = The WarehouseId property is required and cannot be empty. (DSWP0014)
    InvalidUserName = The UserName '{0}' is not valid. UserName must contain an '@' character. (DSWP0015)
    InvalidServicePrincipalName = The ServicePrincipalName '{0}' is not valid. ServicePrincipalName must be a valid GUID. (DSWP0016)
    NoPrincipalSpecified = Each access control entry must specify exactly one principal (GroupName, UserName, or ServicePrincipalName). (DSWP0017)
    MultiplePrincipalsSpecified = Each access control entry must specify only one principal. Cannot specify multiple of GroupName, UserName, or ServicePrincipalName. (DSWP0018)
'@
