ConvertFrom-StringData @'
    EvaluatingSecretScopeState = Evaluating secret scope state for '{0}' in workspace '{1}'. (DSSS0001)
    SecretScopeNotFound = Secret scope '{0}' not found in workspace. (DSSS0002)
    ErrorGettingSecretScope = Error getting secret scope '{0}': {1}. (DSSS0003)
    CreatingSecretScope = Creating secret scope '{0}'. (DSSS0004)
    SecretScopeCreated = Secret scope '{0}' has been created successfully. (DSSS0005)
    ErrorCreatingSecretScope = Failed to create secret scope '{0}': {1}. (DSSS0006)
    RemovingSecretScope = Removing secret scope '{0}'. (DSSS0007)
    SecretScopeRemoved = Secret scope '{0}' has been removed successfully. (DSSS0008)
    ErrorRemovingSecretScope = Failed to remove secret scope '{0}': {1}. (DSSS0009)
    InvalidWorkspaceUrl = The WorkspaceUrl '{0}' is not valid. It must start with 'https://'. (DSSS0010)
    AzureKeyVaultBackendRequired = BackendAzureKeyVault is required when ScopeBackendType is 'AZURE_KEYVAULT'. (DSSS0011)
    InvalidScopeName = The scope name '{0}' is invalid. It must consist of alphanumeric characters, dashes, underscores, and periods, and may not exceed 128 characters. (DSSS0012)
    SecretScopeCannotBeUpdated = Secret scope '{0}' cannot be updated. It will be deleted and recreated. (DSSS0013)
    GettingSecretScope = Getting secret scopes from workspace '{0}'. (DSSS0014)
    ExportingResources = Exporting {0} resources from Databricks workspace. (DSSS0015)
    NoResourcesFound = No {0} resources found in Databricks workspace. (DSSS0016)
    ExportFailed = Failed to export {0} resources: {1}. (DSSS0017)
'@
