ConvertFrom-StringData @'
    EvaluatingGroupState = Evaluating the state of the group '{0}' on workspace '{1}'. (DG0001)
    GroupNotFound = The group '{0}' was not found in the workspace. (DG0002)
    ErrorGettingGroup = Failed to get the group '{0}': {1}. (DG0003)
    CreatingGroup = Creating the group '{0}' in the workspace. (DG0004)
    GroupCreated = Successfully created the group '{0}'. (DG0005)
    FailedToCreateGroup = Failed to create the group '{0}': {1}. (DG0006)
    RemovingGroup = Removing the group '{0}' from the workspace. (DG0007)
    GroupRemoved = Successfully removed the group '{0}'. (DG0008)
    FailedToRemoveGroup = Failed to remove the group '{0}': {1}. (DG0009)
    UpdatingGroup = Updating the group '{0}' in the workspace. (DG0010)
    GroupUpdated = Successfully updated the group '{0}'. (DG0011)
    FailedToUpdateGroup = Failed to update the group '{0}': {1}. (DG0012)
    InvalidWorkspaceUrl = The WorkspaceUrl '{0}' is not valid. It must start with 'https://'. (DG0013)
    InvalidDisplayName = The DisplayName cannot be empty or contain only whitespace. (DG0014)
    ExportingResources = Exporting all resources of type '{0}' from the workspace. (DG0015)
    NoResourcesFound = No resources of type '{0}' were found in the workspace. (DG0016)
    ExportedResourceCount = Exported {0} resource(s) of type '{1}' from the workspace. (DG0017)
    ExportFailed = Failed to export resources of type '{0}': {1}. (DG0018)
'@
